<?php

use App\Models\Ingredient;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $ingredients = [
            'Pomidory w puszce',
            'Cebula',
            'Czosnek',
            'Oliwa z oliwek',
            'Masło',
            'Mąka pszenna',
            'Mąka żytnia',
            'Mąka kukurydziana',
            'Cukier',
            'Sól',
            'Pieprz czarny',
            'Bazylia',
            'Oregano',
            'Rozmaryn',
            'Tymianek',
            'Papryka słodka',
            'Papryka ostra',
            'Kumin',
            'Curry',
            'Kurkuma',
            'Imbir świeży',
            'Imbir mielony',
            'Gałka muszkatołowa',
            'Chili',
            'Kolendra świeża',
            'Kolendra mielona',
            'Koperek',
            'Natka pietruszki',
            'Mięta',
            'Kminek',
            'Liść laurowy',
            'Ziele angielskie',
            'Ocet balsamiczny',
            'Ocet jabłkowy',
            'Ocet winny',
            'Sos sojowy',
            'Sos Worcestershire',
            'Sos ostrygowy',
            'Sos rybny',
            'Miód',
            'Jogurt naturalny',
            'Śmietana 30%',
            'Śmietana 18%',
            'Ser mozzarella',
            'Ser cheddar',
            'Ser feta',
            'Ser parmezan',
            'Ser ricotta',
            'Ser gorgonzola',
            'Ser camembert',
            'Ser brie',
            'Ser pleśniowy',
            'Makaron spaghetti',
            'Makaron penne',
            'Makaron fusilli',
            'Makaron lasagne',
            'Ryż biały',
            'Ryż brązowy',
            'Ryż jaśminowy',
            'Ryż basmati',
            'Kasza gryczana',
            'Kasza jaglana',
            'Kasza bulgur',
            'Kasza kuskus',
            'Soczewica czerwona',
            'Soczewica zielona',
            'Ciecierzyca',
            'Fasola czerwona',
            'Fasola biała',
            'Fasola czarna',
            'Fasolka szparagowa',
            'Ziemniaki',
            'Bataty',
            'Marchew',
            'Por',
            'Seler naciowy',
            'Seler korzeniowy',
            'Papryka czerwona',
            'Papryka żółta',
            'Papryka zielona',
            'Brokuły',
            'Kalafior',
            'Szpinak świeży',
            'Szpinak mrożony',
            'Cukinia',
            'Bakłażan',
            'Pieczarki',
            'Boczniaki',
            'Grzyby suszone',
            'Kurczak filet',
            'Indyk filet',
            'Wołowina mielona',
            'Wieprzowina mielona',
            'Łosoś świeży',
            'Tuńczyk w puszce',
            'Krewetki',
            'Małże',
            'Maślanka',
            'Chleb pszenny',
            'Chleb żytni',
            'Bułka tarta',
            'Masło klarowane',
            'Masło orzechowe',
            'Margaryna',
            'Olejek waniliowy',
            'Ekstrakt migdałowy',
            'Ekstrakt pomarańczowy',
            'Kakao',
            'Czekolada gorzka',
            'Czekolada mleczna',
            'Czekolada biała',
            'Rodzynki',
            'Żurawina suszona',
            'Morele suszone',
            'Śliwki suszone',
            'Daktyle',
            'Figi suszone',
            'Orzechy włoskie',
            'Orzechy laskowe',
            'Orzechy nerkowca',
            'Orzechy makadamia',
            'Migdały',
            'Pistacje',
            'Płatki owsiane',
            'Płatki kukurydziane',
            'Płatki jaglane',
            'Siemię lniane',
            'Nasiona chia',
            'Nasiona słonecznika',
            'Pestki dyni',
            'Sezam',
            'Mak',
            'Drożdże świeże',
            'Drożdże suszone',
            'Proszek do pieczenia',
            'Soda oczyszczona',
            'Żelatyna',
            'Skrobia ziemniaczana',
            'Skrobia kukurydziana',
            'Cukier puder',
            'Cukier waniliowy',
            'Cukier trzcinowy',
            'Syrop klonowy',
            'Syrop z agawy',
            'Mleko kokosowe',
            'Mleko migdałowe',
            'Mleko sojowe',
            'Mleko owsiane',
            'Mleko ryżowe',
            'Mleko krowie',
            'Jajka kurze',
            'Filet z dorsza',
            'Filet z mintaja',
            'Filet z sandacza',
            'Makrela wędzona',
            'Śledź w oleju',
            'Śledź w śmietanie',
            'Anchois',
            'Kalmary',
            'Ośmiornica',
            'Winogrona',
            'Truskawki',
            'Maliny',
            'Jagody',
            'Borówki',
            'Porzeczki czarne',
            'Porzeczki czerwone',
            'Agrest',
            'Arbuz',
            'Melon',
            'Banan',
            'Pomarańcza',
            'Cytryna',
            'Limonka',
            'Mandarynka',
            'Grejpfrut',
            'Kiwi',
            'Granat',
            'Awokado',
            'Mango',
            'Kokos świeży',
            'Gruszka',
            'Jabłko',
            'Śliwka',
            'Woda mineralna gazowana',
            'Woda mineralna niegazowana',
            'Sok pomarańczowy',
            'Sok jabłkowy',
            'Kefir',
            'Maślanka naturalna',
            'Ser twarogowy chudy',
            'Ser twarogowy półtłusty',
            'Ser twarogowy tłusty',
            'Ser mascarpone',
            'Ser halloumi',
            'Ser paneer',
            'Serek wiejsk',
            'Śmietana kwaśna',
            'Śmietana kremówka',
            'Ser topiony',
            'Masło klarowane ghee',
            'Smalec wieprzowy',
            'Olej rzepakowy',
            'Olej słonecznikowy',
            'Olej z pestek winogron',
            'Olej sezamowy',
            'Olej lniany',
            'Olej arachidowy',
            'Olej z awokado',
            'Olej z orzechów włoskich',
            'Mąka orkiszowa',
            'Mąka gryczana',
            'Mąka ryżowa',
            'Mąka owsiana',
            'Mąka migdałowa',
            'Mąka kokosowa',
            'Kasza manna',
            'Kasza perłowa',
            'Kasza pęczak',
            'Kasza jęczmienna',
            'Ryż arborio (do risotto)',
            'Ryż sushi',
            'Soczewica brązowa',
            'Groch łuskany',
            'Groch cały',
            'Bób',
            'Kiełki',
            'Kapusta biała',
            'Kapusta czerwona',
            'Kapusta pekińska',
            'Kapusta włoska',
            'Kapusta kiszona',
            'Ogórek świeży',
            'Ogórek kiszony',
            'Ogórek konserwowy',
            'Rzodkiewka',
            'Sałata masłowa',
            'Sałata lodowa',
            'Sałata rzymska',
            'Sałata roszponka',
            'Cykoria',
            'Fenkuł',
            'Chrzan świeży',
            'Chrzan tarty',
            'Wasabi',
            'Pomidorki koktajlowe',
            'Kalarepa',
            'Rukola',
            'Szczypiorek',
            'Botwina',
            'Burak ćwikłowy',
            'Burak liściowy',
            'Dynia hokkaido',
            'Dynia piżmowa',
            'Pietruszka korzeń',
            'Pietruszka natka suszona',
            'Rabarbar',
            'Płatki kokosowe',
            'Wiórki kokosowe',
            'Udo z kurczaka',
            'Skrzydełka z kurczaka',
            'Karkówka wieprzowa',
            'Schab wieprzowy',
            'Polędwica wieprzowa',
            'Polędwica wołowa',
            'Antrykot wołowy',
            'Szponder wołowy',
            'Żeberka wieprzowe',
            'Żeberka wołowe',
            'Szynka gotowana',
            'Szynka parmeńska',
            'Szynka serrano',
            'Szynka wędzona',
            'Boczek wędzony',
            'Boczek surowy',
            'Salami',
            'Kabanosy',
            'Parówki',
            'Kiełbasa śląska',
            'Kiełbasa biała parzona',
            'Mortadela',
            'Polędwica łososiowa',
            'Mięso mielone mieszane',
            'Mięso mielone z indyka',
            'Mięso mielone z kurczaka',
            'Jagnięcina',
            'Baranina',
            'Mięso z królika',
            'Filet z dorsza atlantyckiego',
            'Łosoś wędzony na zimno',
            'Łosoś wędzony na gorąco',
            'Tuńczyk świeży',
            'Tuńczyk grillowany',
            'Makrela świeża',
            'Makrela pieczona',
            'Śledź matias',
            'Śledź marynowany',
            'Sardynki w oleju',
            'Sardynki w pomidorach',
            'Paluszki rybne',
            'Tatar wołowy',
            'Carpaccio wołowe',
            'Carpaccio z łososia',
            'Bulion drobiowy',
            'Bulion warzywny',
            'Bulion wołowy',
            'Bulion rybny',
        ];
        foreach ($ingredients as $ingredient) {
            Ingredient::create(['name' => $ingredient]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
